// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Adicione aqui as configurações para outras plataformas (Android, iOS, macOS)
    // se você as registrou no seu projeto Firebase.
    // Exemplo para Android (você precisaria obter esses valores do seu console Firebase):
    // if (defaultTargetPlatform == TargetPlatform.android) {
    //   return android;
    // }
    // Exemplo para iOS (você precisaria obter esses valores do seu console Firebase):
    // if (defaultTargetPlatform == TargetPlatform.iOS) {
    //   return ios;
    // }
    
    // Fallback para web se nenhuma outra plataforma corresponder e kIsWeb for verdadeiro,
    // ou lança um erro se não for web e nenhuma outra plataforma for configurada.
    if (kIsWeb) {
       return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  // Estas são as configurações que você forneceu, convertidas para o formato do Flutter.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdy7USyFnDx3bkmYvlUqYx9eoUZBAKKjM',
    appId: '1:590100081179:web:5219957474ff2416dce6be',
    messagingSenderId: '590100081179',
    projectId: 'geek-arise',
    authDomain: 'geek-arise.firebaseapp.com',
    storageBucket: 'geek-arise.firebasestorage.app', // Corrigido: o JS tinha .appspot.com, mas o bucket geralmente é .app
    measurementId: 'G-0M0P2TLJ4Q', // Adicionado
  );

  // --- Exemplo de como seriam as opções para Android (PREENCHA COM SEUS DADOS REAIS) ---
  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'SUA_API_KEY_ANDROID',
  //   appId: 'SEU_APP_ID_ANDROID',
  //   messagingSenderId: 'SEU_MESSAGING_SENDER_ID_ANDROID',
  //   projectId: 'geek-arise',
  //   storageBucket: 'geek-arise.appspot.com',
  // );

  // --- Exemplo de como seriam as opções para iOS (PREENCHA COM SEUS DADOS REAIS) ---
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'SUA_API_KEY_IOS',
  //   appId: 'SEU_APP_ID_IOS',
  //   messagingSenderId: 'SEU_MESSAGING_SENDER_ID_IOS',
  //   projectId: 'geek-arise',
  //   iosBundleId: 'SEU_IOS_BUNDLE_ID',
  //   storageBucket: 'geek-arise.appspot.com',
  // );
}